ユーザー登録を作りました
takano630/twittercloneapp pull request #1
Opened 2021-12-31 05:05 UTC by takano630

ユーザー登録を作りました。

2022-01-04 05:35 UTC, taisei-13046 reviewed
### お願い
レビュー時には以下の内容を記載してください
- 実行結果の画面(画面録画でもOK)
- テストを実行した結果


全体的に良くできていると思います😄
所々、変数命名が不明確な部分があったので意識してつけるようにしましょう〜
わからない部分があったらなんでも気軽に聞いてください！
最終課題、長くなりますがどうぞよろしくお願いします！

2022-01-04 05:35 UTC, taisei-13046 commented on Template/User_HTML/formpage.html
> +</html>
全てのファイルにおいて、最後は1行空行を挟むようにしましょう！
github上で`no new line at end of file `というエラーが起こっています。
[行末の空白削除と改行は何故しなきゃいけないの？](https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html#toc5)
```suggestion
</html>

```

2022-01-04 05:35 UTC, taisei-13046 commented on Template/User_HTML/formpage.html
> +<!DOCTYPE html>
全てのhtmlファイルで共通する内容はbase.htmlにまとめ共通化しましょう！
[テンプレートを拡張しよう](https://tutorial.djangogirls.org/ja/template_extending/)
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>

  <body>
  </body>
</html>
```
この記述は全て共通だと思います

2022-01-04 05:35 UTC, taisei-13046 commented on user/forms.py
> +class Accountform(UserCreationForm):
Accountformでは、Accountのどの動作をする際のFormなのか分からないため、
(例)`AccountCreateForm`など、実行する内容も含めるといいと思います！

また、pythonの命名規則では、クラスは最初大文字 + 大文字区切りが規則なので
`Accountform` -> `AccountForm`の記述で統一しましょう！
[Python命名規則一覧](https://qiita.com/naomi7325/items/4eb1d2a40277361e898b)

2022-01-04 05:35 UTC, taisei-13046 commented on user/views.py
> +class Start(TemplateView):
Viewの命名は `~~View`の形で統一しましょう！
```suggestion
class StartView(TemplateView):
```

2022-01-04 05:35 UTC, taisei-13046 commented on user/views.py
> +    template_name = "User_HTML/formpage.html"
templateのディレクトリ構成について、
現在`Template/User_HTML`になっていますが大文字が混在しており見づらいので、
`templates/user`にした方がいいと思います

2022-01-04 05:35 UTC, taisei-13046 commented on user/views.py
> +    template_name = "User_HTML/formpage.html"
また、`formpage.html`というよりは、signUpをするtemplateになると思うので、
```suggestion
    template_name = "user/signup.html" 
```
に変更するのはいかがでしょうか？


すでにsignup.htmlがありますが、おそらくそのhtmlはユーザ登録が完了した先の画面だと思いますので、`successed_signup.html`など登録が完了したことがわかる名前にするといいと思います！

2022-01-04 05:35 UTC, taisei-13046 commented on user/tests.py
> +class AccountTest(TestCase):
テストを書いているのは大変素晴らしいと思います！！
命名ですがAccountTestよりは、`AccountCreateTest`にすることで、何をテストしているかを明確にしましょう！

2022-01-04 05:35 UTC, taisei-13046 commented on user/tests.py
> +    self.assertEqual(number,1)
変数名についてですが、一眼見て何を示しているかがわかるのが良いと思います
`test` -> `user`
`number` -> `user_count`
にするのをお勧めします！

testの関数名も、同様に命名を見て何をテストしているのかがわかるのが望ましいです！
numberなど抽象的なのでuser_count(作成されたuserの数)などわかりやすい命名を意識しましょう

#### **テストですが、できればuserの登録に失敗した場合などもtestできるといいと思います！**

2022-01-05 09:10 UTC, takano630 commented
<img width="422" alt="test実行結果" src="https://user-images.githubusercontent.com/83489580/148191353-18ff1738-a73e-4144-a7f7-5250f74a743d.png">
テスト実行結果です

2022-01-05 09:15 UTC, takano630 commented
<img width="957" alt="実行結果(1)" src="https://user-images.githubusercontent.com/83489580/148191785-5f2167a6-4b9d-4e12-a1aa-c4b15ffdfaf1.png">
<img width="960" alt="実行結果(2)" src="https://user-images.githubusercontent.com/83489580/148191800-a506516b-6464-40c3-a6f9-152aa7449f14.png">
<img width="959" alt="実行結果(3)" src="https://user-images.githubusercontent.com/83489580/148191816-ed503f8c-dfee-4af2-a838-fc1f4d381c69.png">
実行結果の画面はこんな感じで大丈夫ですか？間違っていたらすいません

2022-01-05 10:26 UTC, taisei-13046 commented
実行結果の画面はそれで大丈夫です！
ありがとうございます！！

2022-01-05 12:07 UTC, taisei-13046 commented on Template/base.html
> +    <title></title>
継承先のhtmlファイルでtitleを指定する場合は、
```suggestion
    <title>{% block title %}{% endblock %}</title>
```
このように指定して、タイトルを指定するのがいいと思います
特にタイトルを指定する方針がなければこの行は削除していいと思います

2022-01-05 12:07 UTC, taisei-13046 commented on Template/user/signup.html
> +      <input class="btn" type="submit"  value="登録">
```suggestion
      <input class="btn" type="submit" value="登録">
```
空白は1つにしましょう

2022-01-05 12:07 UTC, taisei-13046 commented on user/tests.py
> +   testpeople = Account.objects.create(username='testpeople',email = 'test@test.test',password = 'testpassword',age='1')
変数名は_で繋いだ`test_people`が望ましいです。

2022-01-05 12:07 UTC, taisei-13046 commented on user/tests.py
> +   global testpeople
globalで変数宣言するのではなく、
```python
self.test_people = Account.objects.create(username='testpeople',email = 'test@test.test',password = 'testpassword',age='1')
```
と宣言することによって、その後の関数でもself.test_peopleで使うことができます

2022-01-05 12:07 UTC, taisei-13046 commented on user/tests.py
> +class AccountCreateTest(TestCase):
**このテストは正しく実行できていないと思われます**

画像を送っていただいた通り、テストの結果はクリアしています。
しかし、このテストは直接DBにユーザを作成しており、Formなどを通さずに作成しています。
そこで、方針としてsignUpを実行するurlに対してdataをpostすることでユーザを作成してください

正直自分も初めてテストを書いた時はどのようにしていいかわかりませんでした😅
なので下記のサイトなどを参考に実装してみると感覚がつかめると思います！
[Djangoメモ(20) : ユーザー認証を実装する〜サインアップのテストとフォームの改良](https://wonderwall.hatenablog.com/entry/2018/03/21/190000#%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88)

2022-01-05 12:07 UTC, taisei-13046 commented on requirements.txt
> +Django~=2.2.4
djagnoのversionは現在4.0がリリースされています
2.2.4よりもこちらを使用しましょう！
[How to get Django](https://www.djangoproject.com/download/)

2022-01-05 12:07 UTC, taisei-13046 commented on user/tests.py
> +  def test_form_failed(self):
テストは成功時、失敗時と分けて記述した方がわかりやすくなります
```python
class SuccessfulSignUpTests(TestCase):
# ~~~

class InvalidSignUpTests(TestCase):
# ~~~
```

2022-01-06 02:27 UTC, takano630 commented
<img width="419" alt="test実行結果" src="https://user-images.githubusercontent.com/83489580/148318433-c038eb4d-8f08-44b5-9fd4-38e9e41d3a27.png">
テスト実行結果です！

2022-01-06 14:38 UTC, taisei-13046 commented on user/tests.py
> +class SameNameSignUpTest(TestCase):
このクラスは`InvalidSignUpTest`の中にまとめちゃっていいと思います
つまり、SignUpテストのクラスは`SuccessfulSignUpTest`と`InvalidSignUpTest`の二つのみ作成して,その中でテストケースごとに書くのが良いです

(提案)
```python
class InvalidSignUpTest(TestCase):
  def setUp(self):
  # ~~~
  def test_post_empty_user(self):
  # ~~~
  def test_post_duplicate_username(self):
  # ~~~
```

2022-01-06 14:38 UTC, taisei-13046 commented on user/tests.py
> +class InvalidSignUpTest(TestCase):
この記述だと`InvalidSignUpTest`で一つのパターンしかtestできないと思います。
しかし、`InvalidSignUpTest`では複数の失敗パターンをtestしたいので、
以下の記述の仕方を提案します

```python
class InvalidSignUpTest(TestCase):
  def setUp(self):
    self.url = reverse('signup')

  def test_post_empty_user(self):
    data = {}
    response = self.client.post(self.url, data)
    self.assertEquals(response.status_code,200)
    self.assertFalse(Account.objects.exists())

  def test_post_duplicate_username(self):
  # ~~~~
```
この記述方針なら、複数のtestを試すことができると思います

### その他確かめてほしいテスト
- 短いパスワードのユーザ作成
- @のないemail
- password1とpassword2が一致していない
- 数字だけのpassword
- ユーザ名に似たパスワード
- 一般的すぎるパスワード

2022-01-06 14:38 UTC, taisei-13046 commented on user/tests.py
> +class SuccessfulSignUpTest(TestCase):
postしてユーザが作成された時の
- status_code
- リダイレクト先 (`self.assertRedirects`を使用)
もtestで確かめてみてください

2022-01-06 14:38 UTC, taisei-13046 commented on user/tests.py
> +client = Client()
TestCase 内では self.client でClientクラスにアクセスできるので、
clientにアクセスする際は`self.client`でアクセスしましょう
```suggestion

```

2022-01-08 03:15 UTC, takano630 commented on user/tests.py
> +class SuccessfulSignUpTest(TestCase):
すいません。リダイレクトがあまりよく理解できてなくて．．．
ユーザーを作成したとき、urlが変わるようにしていないんですけど、この場合でもリダイレクトってされているんですかね？

2022-01-08 03:33 UTC, taisei-13046 commented on user/tests.py
> +class SuccessfulSignUpTest(TestCase):
すみません。見落としていました！
urlの変更がないのでリダイレクトの確認は不要です
ただ、今後の実装でSignUpが完了したらTwitterのHomeページとかに遷移する流れになるかなと思うのでその際にはtestをお願いします！

2022-01-08 07:50 UTC, takano630 commented on user/tests.py
> +class SuccessfulSignUpTest(TestCase):
わかりました。
ありがとうございます！

2022-01-08 16:24 UTC, Akinori13 requested changes
よろしくお願いします。コメントしました。
以下に気を付けて修正お願い致します。
- 半角スペース
- インデント（スペース4つになっているか）
- importの順序

2022-01-08 16:24 UTC, Akinori13 commented on Template/start.html
> +        <a href="signup">新規登録</a>
`user/urls.py`でpathにname='signup'を定義しました。DjangoにはURLが変更されても自動的にurlを生成する機能が備わっています。これを用いましょう。
[参照記事](https://ziyuss.jp/django-urls-path/)
[公式ドキュメント](https://docs.djangoproject.com/en/4.0/topics/http/urls/)

2022-01-08 16:24 UTC, Akinori13 commented on Template/start.html
> +{% endblock %}
改行入れるよりまとめた方がスッキリしますし、誤って空白が残らず良いかと思います。

2022-01-08 16:24 UTC, Akinori13 commented on Template/user/successed_signup.html
> +    <a href='.'>最初に戻る</a>
ここもurlを動的に。

2022-01-08 16:24 UTC, Akinori13 commented on Template/user/successed_signup.html
> +{% extends 'base.html' %}
`successed_signup`よりも、`signup_done`、`signup_complete`や`signup_successed`が良いと思います。
なぜなら、機能ごとに並ぶので分かりやすいからです。以下は具体例です。
```
confirm_signup
confirm_password_change
password_change
successed_signup
successed_password_change
signup
```
上記よりも下の方が見やすくありませんか。
```
password_change
password_change_confirm
password_change_done
signup
signup_confirm
signup_done
```

2022-01-08 16:24 UTC, Akinori13 commented on twittercloneapp/settings.py
> +TEMPLATE_DIR = os.path.join(BASE_DIR,"Template")
この位置は参照が分かりづらいので、63行目周辺に書きましょう

2022-01-08 16:24 UTC, Akinori13 commented on twittercloneapp/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, 'static')
こちらも127行目周辺に入れましょう

2022-01-08 16:24 UTC, Akinori13 commented on twittercloneapp/settings.py
> +TEMPLATE_DIR = os.path.join(BASE_DIR,"Template")
ここ以外も空白に気を付けてください。`,`後は半角スペースを入れましょう
```suggestion
TEMPLATE_DIR = os.path.join(BASE_DIR, "Template")
```

2022-01-08 16:24 UTC, Akinori13 commented on twittercloneapp/settings.py
> +TEMPLATE_DIR = os.path.join(BASE_DIR,"Template")
[PEP8のサンプル](https://pep8-ja.readthedocs.io/ja/latest/)を参考にしてみてください。この記事にすべて従う必要はないですが、サンプルに従ってみると標準的なコードになると思います！

2022-01-08 16:24 UTC, Akinori13 commented on user/admin.py
> +from .models import Account
Django自体以外からimportする場合は1行空けておきましょう
```suggestion
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin

from .models import Account
```

2022-01-08 16:24 UTC, Akinori13 commented on user/urls.py
> +    path('',views.StartView.as_view(),name='start'),
StartViewでも伝わるのですが、TopViewの方が適切と思います。なるべく瞬時に判別できる名称の方が良いです。

2022-01-08 16:24 UTC, Akinori13 commented on user/views.py
> +
class間は2行空けましょう

2022-01-08 16:24 UTC, Akinori13 commented on user/views.py
> +    def form_valid(self, form):
ここは1行空けましょう

2022-01-08 16:24 UTC, Akinori13 commented on user/models.py
> +  age = models.IntegerField(null=True)
マイナスも許容されてしまうのは、正だけにしましょう。IntegerField以外を使ってみてください。

2022-01-08 16:24 UTC, Akinori13 commented on user/tests.py
> +   self.test_people = Account.objects.create(username='testpeople',email = 'test@test.test',password = 'testpassword',age='1')
長いので改行しましょう。PEP8を参照してください

2022-01-08 16:24 UTC, Akinori13 commented on user/tests.py
> +class AccountCreateTest(TestCase):
記事を参考にしてもらったと思います。網羅的に書かれていてとても良いです。
ただ分類が少し分かりづらいので整理してもらいたいです。
- テストはViewに対するテストとModelに対するテストの二つがある。
- Viewに対するテストはGET通信時とPOST通信時の二つがある。
- POST通信時のテストはSuccessとFailの二つがある。（成功するテストと失敗することを確認するテスト）
以上を念頭にして、AccountModelTests, SignUpTests（GET通信時）, SignUpSuccessTests（POST通信時）, SignUpFailTests（POST通信時）の四つに分けてください。

2022-01-08 16:24 UTC, Akinori13 commented on user/tests.py
> +    self.assertEqual(response.status_code,200)
GET通信時のテストになります。またステータスだけでなく、レンダリングされているテンプレートも正しいか確認してください。

2022-01-08 16:24 UTC, Akinori13 commented on user/tests.py
> +    self.assertEqual(self.test_people.age,'1')
'testpeople'、'test@test.test'などは動的になるように、setUpでdataとしてまとめて、それを使う形にしましょう。

2022-01-08 16:24 UTC, Akinori13 commented on user/tests.py
> +
StartViewのテストも忘れずにお願いします

2022-01-08 16:24 UTC, Akinori13 commented on user/tests.py
> +class InvalidSignUpTest(TestCase):
以下のテストも追加してください
- usernameがブランク
- emailがブランク
- passwordがブランク
- @が含まれないemail

2022-01-08 16:24 UTC, Akinori13 commented on twittercloneapp/settings.py
> +TEMPLATE_DIR = os.path.join(BASE_DIR,"Template")
templateよりもtemplatesの方が良いと思います。

2022-01-27 02:14 UTC, takano630 commented
テストの実行結果です
<img width="419" alt="test実行結果" src="https://user-images.githubusercontent.com/83489580/151279688-0b717dc7-1c50-4e2a-940f-1a2688707a5d.png">

2022-01-29 12:13 UTC, Akinori13 requested changes
少しコメントしました

2022-01-29 12:13 UTC, Akinori13 commented on user/tests.py
> +
class間は2行、関数は1行などに統一してください

2022-01-29 12:13 UTC, Akinori13 commented on user/tests.py
> +   self.data = {'username':'testpeople', 'email':'test@test.test', 'password':'testpassword', 'age':'1'}
datatとtest_peopleの中身が同じかチェックするならば、dataをtest_peopleよりも前に置いて、そのままdataを作成に用いた方が良いのではないでしょうか

2022-01-29 12:13 UTC, Akinori13 commented on user/tests.py
> +    self.assertTemplateUsed(self.response, 'user/signup.html')
空行を最後に入れてください

2022-01-29 12:13 UTC, Akinori13 commented on user/tests.py
> +    data = {'username':'people','email':'test@test.test','password1':'test','password2':'test','age':'1'}
dataを毎回定義しているのは見づらいので、最初にvalidなdataを定義して、それを上書きする形で共通化するのはどうでしょうか

2022-01-29 12:13 UTC, Akinori13 commented on user/models.py
> +  age = models.PositiveSmallIntegerField(null=True)
blankはデフォルトで`false`です。ユーザーの入力は必須だが、データベースでの登録時は必須ではないのは少し珍しいです。
もちろんこのような実装もありですが、単にユーザーの入力は必須ではないという場合は、`blank=True, null=True`にしてあげましょう

2022-01-30 15:43 UTC, Akinori13 approved these changes

2022-01-30 15:44 UTC, merged