ログイン、ログアウト追加
takano630/twittercloneapp pull request #2
Opened 2022-02-11 01:38 UTC by takano630

ログインとログアウトを作りました。

2022-02-11 01:44 UTC, takano630 commented
<img width="479" alt="login_logout(1)" src="https://user-images.githubusercontent.com/83489580/153525527-c8e21872-81be-429e-aa9e-61956749c48d.png">
<img width="395" alt="login_logout(2)" src="https://user-images.githubusercontent.com/83489580/153525535-c2f56eda-76bc-4312-88c9-13fbe98313da.png">
<img width="395" alt="login_logout(3)" src="https://user-images.githubusercontent.com/83489580/153525542-7edce88c-1958-4ad4-a59c-8c010a2d9391.png">
<img width="397" alt="login_logout(4)" src="https://user-images.githubusercontent.com/83489580/153525553-58d281fa-1f75-4c0a-8906-846bb0236569.png">

2022-02-11 01:55 UTC, takano630 commented on user/tests.py
> +    self.assertTemplateUsed(self.login_response, 'user/home.html')
この部分のテストが失敗になってしまうのですがどこを直したらいいのか教えていただけないでしょうか。
ログインしたときにリダイレクトできてるとは思うんですけど上手くいかなくて...
<img width="716" alt="login_logout_test" src="https://user-images.githubusercontent.com/83489580/153525941-411cde6f-0cb1-43b1-8abe-cf66855356c9.png">

2022-02-11 12:03 UTC, taisei-13046 commented on templates/registration/login.html
> +{% endblock %}
最終行に改行を忘れないようにしましょう！！
習慣化していきましょうね！👍

2022-02-11 12:03 UTC, taisei-13046 commented on user/views.py
> +from django.contrib.auth.mixins import LoginRequiredMixin
Login必須にしたのGoodです！！👍

2022-02-11 12:03 UTC, taisei-13046 commented on user/views.py
> +from asyncio.windows_events import NULL
これってどこかで使ってますか？

2022-02-11 12:03 UTC, taisei-13046 commented on user/tests.py
> +    self.home_url = reverse_lazy('home')
[IMO]
ここは`reverse('home')`でいい気がします！
両者の使い分けを意識していたら教えてください！

2022-02-11 12:03 UTC, taisei-13046 commented on user/tests.py
> +    self.assertTemplateUsed(self.login_response, 'user/home.html')
間違いがないように見えます👀
ただ、一点気になったのは、156行目で`reverse_lazy`を使っていることによって、正しくhomeのurlを取得できていないのでは？と思いました
これに関しては、自分もそこまで知識があるわけではないのですが、
reverseは即時実行に対して、reverse_lazyは遅延実行をする差があるのでそこに起因するのかなと思ったりしました

[Django：redirect関数の違いについてまとめてみた](https://qol-kk.com/wp2/blog/2021/02/16/post-2557/#outline__1_1)

2022-02-11 12:03 UTC, taisei-13046 commented on templates/user/home.html
> +      <a href="logout">ログアウト</a>
logoutの指定も
`<a href="{% url 'top' %}">トップへ戻る</a>`
と同じ指定にしてください

2022-02-11 12:03 UTC, taisei-13046 commented on twittercloneapp/settings.py
> +LOGIN_REDIRECT_URL = 'home'
`LOGOUT_REDIRECT_URL`の指定もできますよ！

2022-02-11 12:03 UTC, taisei-13046 commented on user/tests.py
> +class LoginSuccessTest(TestCase):
## その他テストしてほしい内容
- login失敗時のテスト
  - 存在しないユーザ
  - 間違ったパスワード
- logout時のテスト
- Login指定ないユーザで/homeに遷移した場合にHomeページが見れないことの確認

2022-02-11 12:03 UTC, taisei-13046 commented on user/tests.py
> +    self.login_url = reverse('login')
[MUST]
```python
self.home_url = reverse_lazy('home')
self.login_url = reverse('login')
```
これらは、setUpで定義する方がいい気がします！

2022-02-16 13:58 UTC, takano630 commented
setUpなど変えたりしたんですけど上手くいかなかったです...
runserverで実際に動かしてログインしたときはhttpレスポンスは302になってると思うので、testの書き方がどこか間違ってるんですかね？
<img width="722" alt="test実行結果" src="https://user-images.githubusercontent.com/83489580/154277965-cd8c672c-5388-471a-a82c-04737ac0fed3.png">
<img width="644" alt="http_response" src="https://user-images.githubusercontent.com/83489580/154277979-8b3466ae-5da6-4b48-be0b-d84881bcf5c5.png">

2022-02-19 02:23 UTC, takano630 commented
修正してみたんですけど上手くいきませんでした。
これって、httpレスポンスが302じゃないといけないのに200になってるってことですよね？
<img width="719" alt="test失敗" src="https://user-images.githubusercontent.com/83489580/154782382-a0c77433-980d-405d-8a3b-5d754e5104f7.png">

2022-02-19 02:33 UTC, takano630 commented on user/tests.py
>      self.assertEqual(self.login_response.status_code, 200)
self.login_responseのステータスコードが200になってるってことはここが間違っていてリダイレクトできてないって感じですか？

2022-02-19 07:10 UTC, taisei-13046 commented on user/tests.py
>      self.assertEqual(self.login_response.status_code, 200)
```suggestion
    self.assertEqual(self.login_response.status_code, 302)
```
正しくはこうですね！
login成功時には302responseが返されます！

https://developer.mozilla.org/ja/docs/Web/HTTP/Status/302

2022-02-20 01:41 UTC, takano630 commented
ステータスコードが200になってるってことはloginできてないってことですよね？
self.login_responseが間違ってる感じですか
<img width="520" alt="test結果" src="https://user-images.githubusercontent.com/83489580/154825031-8fd16555-d368-4346-bd2c-efe03b56bb73.png">

2022-02-20 11:05 UTC, taisei-13046 commented on user/tests.py
> +    self.login_data = {'username':'people','password':'testpassword'}
```suggestion
    login_data = {'username':'people','password':'testpassword'}
```
ここではlogin_dataを他で使うことはないので`self.`の形にする必要はないです

2022-02-20 11:09 UTC, taisei-13046 commented
画面遷移を見る限りlogin自体は正しく行われているように思えます。
しかし、指摘いただいたとおり、test上でloginが成功していれば302が返ってくるのが正しいのでテストは失敗しています。
改めてtest.pyを確認してユーザの作成 -> login ができているかの確認をお願いします

2022-02-20 11:14 UTC, taisei-13046 commented
確かめ方としては、例えば
```python
    self.test_people = Account.objects.create(username=self.data['username'],email=self.data['email'],password=self.data['password'],age=self.data['age'])
print(self.test_people)
```
等を実行して一つづつ意図した結果になっているかを確認する方法をすることもあります

2022-02-26 03:17 UTC, takano630 commented
test実行結果です
<img width="420" alt="image" src="https://user-images.githubusercontent.com/83489580/155826854-86d09290-cce9-4802-bb6b-faf376faf33a.png">

2022-02-26 04:34 UTC, taisei-13046 commented on user/tests.py
> +from django.urls import reverse, reverse_lazy
`reverse_lazy`は使っていなければ消しておきましょう

2022-02-26 04:34 UTC, taisei-13046 commented on user/tests.py
> +    self.login_response = self.client.post(self.login_url, self.login_data)
```suggestion
    login_data = {'username':'people', 'password':'testpassword'}
    login_response = self.client.post(self.login_url, self.login_data)
```

setUpで定義する変数以外は`self.`の形で記述しなくていいと思います！

2022-02-26 04:34 UTC, taisei-13046 commented on user/urls.py
> +    path('logout',include('django.contrib.auth.urls')),
```suggestion
    path('login',include('django.contrib.auth.urls')),
    path('logout',include('django.contrib.auth.urls')),
```

これって必要でしょうか？🤔
8行目で定義されている気がします

2022-02-26 04:36 UTC, taisei-13046 commented
testの件解決できたようでよかったです！
レビュワーだけでは気づけないところもあったりするので、
slackやPGritを使って質問する習慣つけると誰かが助けてくれると思います👍

2022-02-28 03:32 UTC, Akinori13 requested changes
とてもよいです！！
コメントしました。

2022-02-28 03:32 UTC, Akinori13 commented on user/views.py
>      def form_valid(self, form):
アカウント登録と同時に自動ログインするように実装しましょう

2022-02-28 03:32 UTC, Akinori13 commented on user/urls.py
> +    path('', include('django.contrib.auth.urls')),
下記が望ましいです。[参照](https://docs.djangoproject.com/en/4.0/topics/auth/default/#module-django.contrib.auth.views)
```suggestion
    path('accounts', include('django.contrib.auth.urls')),
```

2022-02-28 03:32 UTC, Akinori13 commented on user/tests.py
> +    self.client.post(self.login_url, self.login_data)
self.client.login()を用いましょう。
分離しすぎると可読性が下がる可能性がありますので、login_dataは分離しなくても構いません

2022-02-28 03:32 UTC, Akinori13 commented on user/tests.py
> +    self.home_url = reverse('home')
これいらないなら消しちゃってください

2022-02-28 03:32 UTC, Akinori13 commented on user/tests.py
> +    self.home_url = reverse('home')
ハードコーディングは望ましくありませんから（変更に弱いので）、settingsからLOGIN_REDIRECT_URLを代入しましょう。

2022-02-28 03:32 UTC, Akinori13 commented on user/tests.py
> +    self.login_url = reverse('login')
使わない場合は、消しちゃってください

2022-02-28 03:32 UTC, Akinori13 commented on user/tests.py
> +class HomeTest(TestCase):
失敗した時だけでなく成功した時の挙動の確認もしてください

2022-03-02 04:29 UTC, takano630 commented
test実行結果です
<img width="422" alt="image" src="https://user-images.githubusercontent.com/83489580/156295126-aeee7e82-9e72-4eab-92c8-4aa88fe227ba.png">

2022-03-05 02:00 UTC, Akinori13 approved these changes

2022-03-05 02:00 UTC, Akinori13 commented
LGTM

2022-03-05 02:00 UTC, merged