ツイート
takano630/twittercloneapp pull request #4
Opened 2022-03-14 02:20 UTC by takano630

ツイート機能を作りました

2022-03-14 02:22 UTC, takano630 commented
実行結果です
<img width="950" alt="image" src="https://user-images.githubusercontent.com/83489580/158093921-39ce83e8-f4a6-41bb-ac99-e02f684a5584.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/83489580/158093984-da5ef094-8666-481c-96f5-73efd815da90.png">

2022-03-16 08:53 UTC, takano630 commented
test実行結果です
<img width="431" alt="image" src="https://user-images.githubusercontent.com/83489580/158552647-bd46225c-9b88-4ee1-a4e4-8166223b4718.png">

2022-03-16 08:54 UTC, takano630 commented
test実行結果です
<img width="420" alt="image" src="https://user-images.githubusercontent.com/83489580/158552778-5b962395-1b67-4444-9d83-152c58b0e9e4.png">

2022-03-19 01:08 UTC, taisei-13046 commented on user/models.py
> +  text = models.CharField(max_length=200)
[MUST]
```suggestion
  text = models.TextField(max_length=200)
```
ここは、Char(文字)ではなくText(文字列)の方が適切だと思います！

2022-03-19 01:08 UTC, taisei-13046 commented on user/models.py
> +  user = models.ForeignKey('Account', on_delete=models.CASCADE, blank=True)
[Q]
blank=Trueにした意図ってなんでしょうか？🤔

2022-03-19 01:08 UTC, taisei-13046 commented on user/models.py
> +  published_date = models.DateTimeField(default=timezone.now, blank=True)
[MUST]
```suggestion
  published_date = models.DateTimeField(default=timezone.now)
```
blankを許容する必要はない気がします

2022-03-19 01:08 UTC, taisei-13046 commented on templates/user/home.html
> +        <p>---------------------------------------</p>
[WANT]
できればここはcssでやりたいですね！
```css
width: 100%;
htight: 1px;
background-color: "black";
```
みたいな感じで。
(ここはDjangoの課題の範囲を超えているので修正はなくても大丈夫です！👍)

2022-03-19 01:08 UTC, taisei-13046 commented on user/tests.py
> +    self.assertEqual(tweet_number, 1)
[nits]
```suggestion
    self.assertEqual(Tweet.objects.count(), 1)
```
ここの中間変数はなくてもいいかなと思います！
`tweet_number`を複数回使用するときに変数に入れましょう

2022-03-19 01:08 UTC, taisei-13046 commented on user/tests.py
> +    self.assertFalse(tweet_number)
```suggestion
    self.assertEqual(Tweet.objects.count(), 0)
```
[nits]
このほうがツイートが存在しない(0個である)ことが明確でわかりやすいな〜と思いました！

2022-03-19 01:08 UTC, taisei-13046 commented on user/views.py
> +class TweetView(LoginRequiredMixin, TemplateView):
[MUST]
ここはDjangoのCreateViewを使って書いてみましょう！
もっとスッキリ描けると思います

https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/#createview

2022-03-19 01:08 UTC, taisei-13046 commented on user/tests.py
> +  def test_tweet_succese(self):
[MUST]
```suggestion
  def test_tweet_success(self):
```
typoですね

2022-03-19 01:08 UTC, taisei-13046 commented on user/tests.py
> +
[Q]
2つ空行が入ってますかね？

2022-03-20 11:51 UTC, takano630 commented on user/models.py
> +  user = models.ForeignKey('Account', on_delete=models.CASCADE, blank=True)
textだけ書いてpostする感じにしたので他二つが「blank=true」でないとpostした時に「form.is_valid」になってくれなかったからです。

2022-03-21 12:47 UTC, takano630 commented
cssを付け加えようとしたんですけどどうしてもうまくいかなくて...
どこを修正すればいいですかね
<img width="443" alt="image" src="https://user-images.githubusercontent.com/83489580/159263737-8a1a6d5a-eb0e-4d49-ac28-84505046060d.png">

2022-03-24 01:11 UTC, takano630 commented
この部分にcssをつけたいんですけど上手くいかない感じです
色々調べて「setting.py」とか「home.html」とかいじってみたんですけど「home_style.css」が見つからないんです。
「home_style.css」の場所は「static/css/home_style.css」であってると思うんですけど...
<img width="948" alt="image" src="https://user-images.githubusercontent.com/83489580/159821415-6f2eeec2-3028-4979-ac19-e69558d76fcd.png">

2022-03-27 01:16 UTC, taisei-13046 commented
@takano630 直接的な回答になっていないのですが、以下のサイトを見てもう一回やってみてください！
https://tutorial.djangogirls.org/ja/css/

ちなみに今pushされているcommit内ではcssファイルが見当たらないんですが、正しく作成されていないかもですね？

2022-03-30 02:32 UTC, takano630 commented
<img width="955" alt="image" src="https://user-images.githubusercontent.com/83489580/160739169-e349b57a-5209-4e25-9653-dffa5fd59a35.png">

2022-04-01 10:03 UTC, Akinori13 requested changes
よくできています！！
- Tweetは削除機能も作成してください。
- userアプリのままでも構いませんが、本来はツイートアプリを作成した方がよいです
- インデントがそろっていないことがあるので、注意しましょう
- migrationsがルートに来ていますが、これは想定通りの配置ですか

2022-04-01 10:03 UTC, Akinori13 commented on templates/user/home.html
> +        <h3>{{ tweet.text }}</h3>
ツイートの改行も表示できるようにしましょう

2022-04-01 10:03 UTC, Akinori13 commented on templates/user/tweet.html
> +  <input type="submit" value="送信">
この実装の場合エラーは表示されていますか

2022-04-01 10:03 UTC, Akinori13 commented on twittercloneapp/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, 'static')
二つあります

2022-04-01 10:03 UTC, Akinori13 commented on user/forms.py
> +
何行空けるかは任意にしますが、少なくとも統一はしましょう

2022-04-01 10:03 UTC, Akinori13 commented on user/models.py
> +  user = models.ForeignKey('Account', on_delete=models.CASCADE, blank=True)
forms.pyのTweetCreateFormのMetaクラスのfieldsから、`user`, `pulished_date`を抜きましょう。
fieldsの項目は、formの要素に反映され、バリデーションの対象となります。今回はuserとpublished_dateはのちに追加する項目ですからいりません

2022-04-01 10:03 UTC, Akinori13 commented on user/models.py
> +  published_date = models.DateTimeField(default=timezone.now, blank=True)
任意ですが、created_atやupdated_atの方が、統一されてよいかとも思われます

2022-04-01 10:03 UTC, Akinori13 commented on user/views.py
> +      tweet.published_date = timezone.now()
いらないです

2022-04-01 10:03 UTC, Akinori13 commented on user/views.py
> +
最終行は空行にしましょう

2022-04-02 09:23 UTC, takano630 commented on templates/user/tweet.html
> +  <input type="submit" value="送信">
エラーは多分出ていないんですけど、何か改善したほうがいいところがある感じですかね？

2022-04-12 04:55 UTC, takano630 commented
削除画面です
<img width="943" alt="image" src="https://user-images.githubusercontent.com/83489580/162883254-3614c78b-2fdf-44c9-93ad-53413685877e.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/83489580/162883440-faa307e9-b48f-4e91-b787-53422f4c2808.png">

2022-04-12 05:40 UTC, takano630 commented
test実行結果です
<img width="429" alt="image" src="https://user-images.githubusercontent.com/83489580/162888538-2cd932b0-5101-42bd-9d9e-6b807d0b7633.png">

2022-04-13 15:43 UTC, Akinori13 requested changes
いくつかコメントしました。確認お願いします！

2022-04-13 15:43 UTC, Akinori13 commented on user/views.py
> +class DeleteTweetView(DeleteView, LoginRequiredMixin):
削除Viewでは、投稿した本人のみが削除できるようにしてください

2022-04-13 15:43 UTC, Akinori13 commented on user/models.py
> +  published_at = models.DateTimeField(default=timezone.now, blank=True)
ここのブランクも再度確認してください。

2022-04-22 13:58 UTC, takano630 commented on templates/user/home.html
> +        {% endif %}
loginしてるアカウントの名前とツイートの投稿主の名前が一致したら「削除」が出るようにしたいんですけど、これだと上手くいきませんでした。「tweet.user」と「user.username」をそれぞれ表示させてみると想定通りの物が出てきました。

2022-04-22 15:54 UTC, Akinori13 commented on templates/user/home.html
> +        {% endif %}
質問ありがとうございます！！
ここは難所の一つですね！「UserPassesTestMixin」で調べてみてください！


さて、フロントエンドでユーザーの行動を制限しようとしないことを覚えておいてください。
善意のユーザーには、このリンクは表示されないので問題はありません。しかし悪意のユーザーは、このTweetのIDを知っていれば、削除できてしまいます。

このような権限の問題やバリデーションはバックエンドで実装します。もちろんフロントエンドはする必要がないとは言いません。しかしフロントエンド側でユーザーの行動を制限することはユーザー体験の向上が目的で、バックエンドでの制限はセキュリティと安全な運用が目的です。


また分からないところがあれば遠慮なく！

2022-05-02 13:56 UTC, Akinori13 requested changes
コメントしました

2022-05-02 13:56 UTC, Akinori13 commented on user/views.py
> +
空行の行数をそろえます

2022-05-02 13:56 UTC, Akinori13 commented on user/views.py
> +from urllib import request
使わないものは消してください

2022-05-02 13:56 UTC, Akinori13 commented on user/views.py
> +    return redirect('home')
インデントそろえてください

2022-05-02 13:56 UTC, Akinori13 commented on user/views.py
> +     return (tweet.user == self.request.user)
```suggestion
     return tweet.user == self.request.user
```

2022-05-02 13:56 UTC, Akinori13 commented on user/views.py
> +  def test_func(self, **kwargs):
```suggestion
  def test_func(self):
```

2022-05-02 13:56 UTC, Akinori13 commented on user/tests.py
> +class TweetSucceseTest(TestCase):
[これ](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit?usp=sharing)みてテスト追記してください

2022-05-03 13:21 UTC, takano630 commented on user/tests.py
> +class TweetSucceseTest(TestCase):
アクセス権がないみたいで見れないです...

2022-08-06 02:09 UTC, takano630 commented
test実行結果です
<img width="443" alt="image" src="https://user-images.githubusercontent.com/83489580/183229467-c62cb2ee-104f-456c-826b-9becdc000b2d.png">

2022-08-06 07:12 UTC, Akinori13 requested changes
いくつかコメントしました

2022-08-06 07:12 UTC, Akinori13 commented on templates/user/update.html
> +{% endblock %}
空行

2022-08-06 07:12 UTC, Akinori13 commented on user/views.py
> +class ProfileView(LoginRequiredMixin, TemplateView):
profileは他のユーザーも閲覧できるようにします。
profiles/userAでuserAの情報が、profiles/userBでuserBの情報が表示されるイメージです

2022-08-06 07:12 UTC, Akinori13 commented on user/views.py
> +    return tweet.user == self.request.user
以下でできませんか
```suggestion
    return self.object.user == self.request.user
```

2022-08-06 07:12 UTC, Akinori13 commented on user/views.py
> +class AccountUpdateView(LoginRequiredMixin, UpdateView):
DeleteTweetViewと同様に自分のプロフィールだけを削除できるようにして下さい

2022-08-07 13:11 UTC, takano630 commented on user/views.py
> +    return tweet.user == self.request.user
<img width="561" alt="image" src="https://user-images.githubusercontent.com/83489580/183292242-5a35764b-5759-4c80-a656-838fda09dc30.png">
エラーが出てしまいました

2022-08-07 14:12 UTC, takano630 commented
実行結果です
<img width="440" alt="image" src="https://user-images.githubusercontent.com/83489580/183294906-c204e676-bbfa-43f2-8169-a1dc3d3ccaca.png">

2022-08-08 09:04 UTC, Akinori13 commented on user/views.py
> +    return tweet.user == self.request.user
ごめんなさい！！！！！勘違いしてました！
以下でいけるはずです！
```suggestion
    tweet = self.get_object()
    return tweet.user == self.request.user
```

2022-08-08 09:10 UTC, Akinori13 requested changes
いくつかコメントしました。それから空行の数をそろえてください。
いい感じです！もう少しで次のステップに行けます！

2022-08-08 09:10 UTC, Akinori13 commented on user/views.py
> +from django.urls import reverse_lazy, reverse
いらないimportは削除してください

2022-08-08 09:10 UTC, Akinori13 commented on user/tests.py
> +class TweetFailTest(TestCase):
テスト足りてないです。最終課題テスト項目要件整理を確認してください

2022-08-08 09:10 UTC, Akinori13 commented on user/tests.py
> +    self.tweet_delete_url = '/1/delete'
ハードコーディングしない

2022-08-08 09:10 UTC, Akinori13 commented on user/tests.py
> +class UpdateSucceseTest(TestCase):
命名。`Profile`を入れる

2022-08-09 12:46 UTC, takano630 commented
存在しないユーザーのプロフィールの取得に関するテストを書きたいのですが以下のエラーが出てしまいました。存在しないユーザーなのでクエリセットがないのはわかるのですがエラーを回避するためにはどこを修正すべきでしょうか？
よろしくお願いします。
<img width="838" alt="image" src="https://user-images.githubusercontent.com/83489580/183649021-5b918a5e-7edf-4422-a680-5d3ddc9a80fc.png">

2022-08-12 05:56 UTC, Akinori13 commented
おおむね検討した事項はあってます！
ProfileViewではユーザーが見つからなかったときは404を返してあげましょう

2022-08-13 01:46 UTC, takano630 commented
ありがとうございます解決しました！
test実行結果です
<img width="428" alt="image" src="https://user-images.githubusercontent.com/83489580/184463919-2276ad93-6bbf-4cbe-bf20-e14d03128b52.png">

2022-08-13 08:48 UTC, Akinori13 requested changes
いい感じです！！！！！！！ちょっといくつかコメントが解消されていないので、再確認してください！！

2022-08-13 08:48 UTC, Akinori13 commented on templates/user/tweet.html
> +  <input type="submit" value="送信">
ごめんなさい！質問見落としてました！エラーを表示できるようにしてください！！

2022-08-13 08:48 UTC, Akinori13 commented on templates/user/tweet.html
> +  <input type="submit" value="送信">
https://docs.djangoproject.com/en/4.1/ref/forms/api/

2022-08-13 08:48 UTC, Akinori13 commented on user/views.py
> +      return redirect('tweet')
フォームにエラーが含まれる場合はエラーメッセージを表示して欲しいのでelse以下は必要ないです

2022-08-15 05:08 UTC, takano630 commented
エラーメッセージってこれですか？
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/184579630-c5f4d747-52f7-4c47-9fc8-d126535509e0.png">

2022-08-16 14:18 UTC, Akinori13 commented
> エラーメッセージってこれですか？ <img alt="image" width="960" src="https://user-images.githubusercontent.com/83489580/184579630-c5f4d747-52f7-4c47-9fc8-d126535509e0.png">

ではないです！[参考記事](https://itc.tokyo/django/form-validation/)です。こちらをご確認ください！

2022-08-16 14:20 UTC, Akinori13 commented
user/tests.pyにいくらかコメントがあるはずです。そちらも修正してください！

2022-08-18 02:43 UTC, takano630 commented
form.py のvalidationに関するテストでエラーが出てしまいました。
「text」の値が「None」になってるからエラーになってるっぽいんですけど、「print(text)」を使ってみたらちゃんと「test.py」通りに「test」が出力されました。
<img width="720" alt="image" src="https://user-images.githubusercontent.com/83489580/185280555-928cfe9b-f692-41c6-b2d5-04fbbd286d5d.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/83489580/185280616-a5577bd7-3891-46ab-a7b9-5e0962959a5b.png">

2022-08-20 09:19 UTC, Akinori13 commented
> form.py のvalidationに関するテストでエラーが出てしまいました。 「text」の値が「None」になってるからエラーになってるっぽいんですけど、「print(text)」を使ってみたらちゃんと「test.py」通りに「test」が出力されました。 <img alt="image" width="720" src="https://user-images.githubusercontent.com/83489580/185280555-928cfe9b-f692-41c6-b2d5-04fbbd286d5d.png"> <img alt="image" width="721" src="https://user-images.githubusercontent.com/83489580/185280616-a5577bd7-3891-46ab-a7b9-5e0962959a5b.png">

まずは問題を細分化して取り組んでみましょう！
textがNoneになっているからエラーになるのは想定通りではありませんか？問題なのはエラーが発生するPOSTを適切に対処できていないことです。ではどのようなエラーが発生しているか読みましたか。
```
ValueError: The view user.views.view didn't return an HttpResponse object. It returned None instead.
```
異常なPOSTに対してHTTPレスポンスを返していないということです。`if form.is_valid():`がFalseの場合は考慮していますか。考慮してHTTPレスポンスを返せるようにしましょう。


その上でですが補助的なコメントです。
①[一般的な実装](https://igreks.jp/dev/django-createview%E3%82%84updateview%E5%88%A9%E7%94%A8%E6%99%82%E3%80%81%E4%BB%BB%E6%84%8F%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E8%A3%8F%E5%81%B4%E3%81%A7%E4%BF%9D%E5%AD%98%E3%81%99%E3%82%8B/)はpost()を上書きするよりもform_valid()を上書きすると思います。
②もしpostを上書きする場合は、処理を追ってあげましょう。
CreateViewはBaseCreateViewのpostを継承します。そこでは以下のようなコードがあります。どのような意味合いがあるのかを把握しておきましょう。特にみてあげるべきなのは、`SingleObjectMixin`の`get_context_data`です
```
self.object = None
```

2022-08-20 13:07 UTC, takano630 commented
解決しました！ありがとうございました。
<img width="449" alt="image" src="https://user-images.githubusercontent.com/83489580/185747466-cb043d73-fbee-4389-987b-c4559c14617d.png">

2022-08-23 12:13 UTC, Akinori13 requested changes
あと少しです！

2022-08-23 12:13 UTC, Akinori13 commented on user/views.py
> +from django.urls import reverse_lazy, reverse
いらないimportが入っているので削除してください

2022-08-23 12:13 UTC, Akinori13 commented on user/forms.py
> +        return text
ここmodelをblack=false, null=falseにしてあげればよいと思います！
それから文字数超過もmodelで対応済みなのでいらないかと！

2022-08-23 12:13 UTC, Akinori13 commented on user/forms.py
> +        return text
というかデフォルトでblack=false, null=falseなので指定する必要もないですね

2022-08-23 12:13 UTC, Akinori13 commented on user/tests.py
> +  def test_failure_post_with_incorrect_user(self):
403チェックをお願いします

2022-08-23 12:13 UTC, Akinori13 commented on user/tests.py
> +class UpdateSucceseTest(TestCase):
これもう一度確認！

2022-08-23 12:13 UTC, Akinori13 commented on user/tests.py
> +    self.client.login(username='people', password='testpassword')
```suggestion
     self.user = Account.objects.create_user(username='people', email='test@test.test', password='testpassword', age='1')
    self.home_url = reverse('home')
    self.tweet = Tweet.objects.create(user=self.user, text='text')
    self.tweet_delete_url = '/'+str(self.tweet.pk)+'/delete'
    self.client.login(username='people', password='testpassword')
```

2022-08-23 12:13 UTC, Akinori13 commented on user/tests.py
> +    self.client.login(username='people', password='testpassword')
あと、こんな感じで書けるはずです（あくまで例です）
```
self.tweet_delete_url = reverse("tweets:delete", kwargs={"pk": self.tweet.pk})
```

2022-08-23 12:54 UTC, takano630 commented on user/tests.py
> +  def test_failure_post_with_incorrect_user(self):
ログインしているユーザーと違うユーザーのツイートを削除しようとしたら「home」にリダイレクトするようにしてるんですけどそこから修正するべきですか？

2022-08-23 13:21 UTC, takano630 commented
テスト実行結果です
<img width="456" alt="image" src="https://user-images.githubusercontent.com/83489580/186168759-e4418b08-90b8-4b4d-ac9c-ea58772e6d81.png">

2022-08-23 13:27 UTC, takano630 commented on user/views.py
> +from django.urls import reverse_lazy, reverse
3つとも使用しているんですけどどうすればいいですか？
import消したらエラーが出てしまいました。

2022-08-23 13:32 UTC, takano630 commented on user/views.py
> +from django.urls import reverse_lazy, reverse
> 3つとも使用しているんですけどどうすればいいですか？ import消したらエラーが出てしまいました。

2022-08-23 13:35 UTC, takano630 commented
user/views.py の必要のないimportを消す件について、指摘された３つとも使用しているのですがどうすればいいですか？

2022-08-26 22:23 UTC, Akinori13 commented on user/tests.py
> +  def test_failure_post_with_incorrect_user(self):
あっ、そしたら実装に合わせて修正しなくて大丈夫です！可能ならテスト項目要件整理に合わせて書いてもらえるとありがたいです

2022-08-26 22:25 UTC, Akinori13 commented
> user/views.py の必要のないimportを消す件について、指摘された３つとも使用しているのですがどうすればいいですか？

もしかしたら見間違いかもしれないんですけど、user.views.pyでは、reverseとFormViewが使われてないと思います....
もう一度確認貰いたいです

![スクリーンショット (234)](https://user-images.githubusercontent.com/65198192/186998311-ebb8f4d5-e67e-4090-8f16-7990268f1f55.png)

2022-08-27 02:16 UTC, takano630 commented
> > user/views.py の必要のないimportを消す件について、指摘された３つとも使用しているのですがどうすればいいですか？
> 
> もしかしたら見間違いかもしれないんですけど、user.views.pyでは、reverseとFormViewが使われてないと思います.... もう一度確認貰いたいです
> 
> ![スクリーンショット (234)](https://user-images.githubusercontent.com/65198192/186998311-ebb8f4d5-e67e-4090-8f16-7990268f1f55.png)

見逃してました...
ありがとうございます

2022-08-27 03:36 UTC, Akinori13 approved these changes

2022-08-27 03:37 UTC, merged