フォロー機能
takano630/twittercloneapp pull request #6
Opened 2022-08-29 01:20 UTC by takano630

2022-08-29 13:26 UTC, takano630 commented
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/187211543-63abe28e-a663-49b8-bffa-2d593dfc0a64.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/187211683-69bf4274-ca9b-4b70-a9eb-8a73a4f9e8a7.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/187211971-ccb559a8-38b7-4b0b-82e2-ab9534571dbc.png">

2022-08-29 13:36 UTC, takano630 commented
test実行結果です。一部わからないところがあったのでアドバイスもらえたら幸いです
<img width="700" alt="image" src="https://user-images.githubusercontent.com/83489580/187213711-afebe2b3-40b9-4528-8612-8787ea4639cd.png">

2022-08-29 13:42 UTC, takano630 commented on user/tests.py
> +    self.assertEqual(self.people.follow.all().count(), 1)
<img width="514" alt="image" src="https://user-images.githubusercontent.com/83489580/187214256-2db6ef61-93eb-4989-a8a2-06f393dbb583.png">
ユーザーを二つ作成して片方にログインしてもう片方をフォローするようにしてテストしたんですけど、うまくいかなくて修正すべき箇所が見当がつきません。どこを修正すべきでしょうか

2022-08-29 13:47 UTC, takano630 commented on user/tests.py
> +    self.assertEqual(self.people.follow.all().count(), 0)
<img width="629" alt="image" src="https://user-images.githubusercontent.com/83489580/187215363-c439734e-9de3-416d-bd5c-06cefdee9c00.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/83489580/187215907-428f343c-95ec-451d-aaa3-b064db06607a.png">
存在しないユーザーをフォローしようとしたときのテストです。実際に動かしたときは「status_code」が404になっているので間違っているのはtestの方だとは思うんですがどこを修正すべきでしょうか。

2022-08-30 01:55 UTC, okapiinosuke commented on user/tests.py
> +    self.assertEqual(self.people.follow.all().count(), 1)
カウントが増えず、リダイレクトできているということは、フォローしている人とされている人が同一人物の場合に当たるのではないかと思われます。実際にどの分岐に遷移しているかをprint文で確認してみるといいと思います。

2022-08-30 01:55 UTC, okapiinosuke commented
コメントしました。
最終課題要件を再確認しながら修正すると良いと思います。
https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=128988789

2022-08-30 01:57 UTC, okapiinosuke commented on user/tests.py
> +    self.assertEqual(self.people.follow.all().count(), 0)
こちらもどういった分岐になっているかをprint文で確認するとよいと思います。フォローしている人とフォローされている人が想定通りに、変数に代入されているか確認してみてください。

2022-08-30 02:09 UTC, okapiinosuke reviewed
コメントしました。
最終課題要件を確認しながら、修正していきましょう。
https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917

2022-08-30 02:09 UTC, okapiinosuke commented on templates/user/followlist.html
> +      <p>{{ follow.username }}</p>
followじゃなく、「フォロー関係の一覧」を表した変数名にしましょう。

2022-08-30 02:09 UTC, okapiinosuke commented on user/models.py
> +  follow = models.ManyToManyField('self', related_name = 'followed', symmetrical = False, blank = True)
フォロー関係は別のモデルで定義しましょう。
この部分の変更は、今回実装した範囲にかなり影響を与えるので、気を付けて修正してください！

2022-08-30 02:09 UTC, okapiinosuke commented on user/views.py
> +  def get(self, request, *args, **kwargs):
フォロー関係を作成するので、post時にこの操作を行いましょう。最終課題の要件を確認してください。

2022-08-30 02:09 UTC, okapiinosuke commented on user/views.py
> +    return user_profile.follow.all()
パフォーマンスを意識した書き方をしてみましょう。
ツイート取得の時と同じです。

2022-08-30 02:09 UTC, okapiinosuke commented on user/views.py
> +      user.follow.remove(follow_user)
UnfollowViewを別で作成して実装しましょう。（最終課題要件を確認）

2022-08-30 02:09 UTC, okapiinosuke commented on user/views.py
> +    context['follower'] = user_profile.followed.all().count()
こちらもパフォーマンスを意識しましょう。allの多用は控えたほうが良いと思います。

2022-08-30 02:09 UTC, okapiinosuke commented on user/tests.py
> +  def test_succese_get(self):
フォロー数の増減がちゃんとできているかどうか確認してみると良いと思います。

2022-08-30 02:09 UTC, okapiinosuke commented on user/tests.py
> +  def test_succese_get(self):
フォロー数の時と同様

2022-08-30 02:09 UTC, okapiinosuke commented on user/tests.py
> +class FollowSucceseTest(TestCase):
スペルミス
Succese→Success

2022-09-01 07:55 UTC, takano630 commented on user/views.py
> +  def get(self, request, *args, **kwargs):
今はプロフィール画面で「follow」のurlを押したときに「Followview」でフォローしてすぐにプロフィール画面にリダイレクトする感じになっているんですけど、「profileview」でpost時にフォローの動作をするってことですか？

2022-09-01 07:58 UTC, takano630 commented
パフォーマンスについて自分なりに調べて修正してみたんですけどまだあまり理解していないので、アドバイスいただければ幸いです

2022-09-01 10:09 UTC, okapiinosuke reviewed
コメントしました。
変数の名前を付けるときには、「一目見ただけで何を意味しているかがわかる」ようにしましょう。
最初の方は、どのように名前付けするかが難しいと思うので、以下のページでどのように名前付けされるかを見てみるとよいと思います。
https://codic.jp/engine

2022-09-01 10:09 UTC, okapiinosuke commented on templates/user/followerlist.html
> +      <p>{{ follower.user.username }}</p>
object_listだと何のリストかが不明瞭なのでfollower_listにしましょう。

2022-09-01 10:09 UTC, okapiinosuke commented on templates/user/followlist.html
> +      <p>{{ following_user.username }}</p>
followerの時と同様

2022-09-01 10:09 UTC, okapiinosuke commented on templates/user/profile.html
> +    <p>フォロー数 : {{ following }}</p>
これもfollowingだけだと何かわからないので、変数を見ただけで「フォロー数」とわかるような変数の名前付けをしてみましょう。

2022-09-01 10:09 UTC, okapiinosuke commented on templates/user/profile.html
>      <p>フォロワー数 : {{ follower }}</p>
これもフォロワー数が変数名からわかるように変更しましょう。

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +  def get(self, request, *args, **kwargs):
そうですね。
ProfileViewにあるFollowボタンを押したときにpostの動作をするようにして、Follow関係を作るようにしてください。
（理解が間違っていたら返信してください）

2022-09-01 10:09 UTC, okapiinosuke commented on user/models.py
> +   follow = models.ManyToManyField('Account', related_name = 'followed', symmetrical = False, blank = True)
フォロー関係は外部で定義されたクラスを用いるので、ForeignKeyを利用して実装しましょう。
「Django 中間テーブル」という風に検索すると例が出てくるので、そこでなぜこのような形をとるのかを理解するとよいと思います。

2022-09-01 10:09 UTC, okapiinosuke commented on user/models.py
> +class Follow(models.Model):
フォロー関係を表す名前にしましょう。

2022-09-01 10:09 UTC, okapiinosuke commented on user/models.py
> +   user = models.OneToOneField('Account', on_delete=models.CASCADE)
user→follower

2022-09-01 10:09 UTC, okapiinosuke commented on user/models.py
> +   follow = models.ManyToManyField('Account', related_name = 'followed', symmetrical = False, blank = True)
follow→followee

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +      pass
この部分は関係を作成する前に持っていきましょう

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +      my_follow[0].follow.add(follow_user)
なくても大丈夫です。

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +    my_follow = Follow.objects.get_or_create(user = user)
get_or_createの返り値は1つではありません。書き方を変えましょう。
一方の返り値をつかうと重複チェックができます。
また、ForeignKeyを使うと書き方が少し変わるので注意

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +    my_follow = Follow.objects.get_or_create(user = user)
FollowViewの時と同様

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +    return my_follow[0].follow.all().select_related()
prefetch_relatedの使い方を調べて、使ってみましょう。
またその時に、select_relatedと何が違うかを知ると理解が深まるかもしれません。

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +    return user.followed.prefetch_related("user").all()
prefetch_relatedの使い方を調べてみましょう。

2022-09-01 10:09 UTC, okapiinosuke commented on user/views.py
> +    return my_follow[0].follow.prefetch_related("user").all()
prefetch_relatedの使い方を調べてみましょう。

2022-09-02 00:46 UTC, takano630 commented on user/views.py
> +      my_follow[0].follow.add(follow_user)
addしなくていいってことですか？

2022-09-02 01:01 UTC, okapiinosuke commented on user/views.py
> +      my_follow[0].follow.add(follow_user)
そうですね。
createした時点で恐らく追加されるはずです。

2022-09-02 01:35 UTC, takano630 commented on user/views.py
> +      my_follow[0].follow.add(follow_user)
追加されませんでした...

2022-09-02 01:44 UTC, takano630 commented on user/tests.py
> +    self.follow_response = self.client.post(self.profile_url, {"follow_or_unfollow": "follow_or_unfollow"})
フォローのテストでボタンを押してpostするレスポンスの書き方がわかりません
調べ方が悪いのか全然出てこなくて...
一応下のサイトを参考にしてpostするデータを「{ name : value}」みたいにしたんですけどダメでした
https://stackoverflow.com/questions/4217930/unit-testing-a-django-form-containing-multiple-submit-buttons

2022-09-02 01:47 UTC, takano630 commented on user/tests.py
> +    self.follow_response = self.client.post(self.profile_url, {"follow_or_unfollow": "follow_or_unfollow"})
buttonだけでformがないときのpostのデータの部分の書き方です

2022-09-02 07:50 UTC, okapiinosuke commented on user/tests.py
> +    self.follow_response = self.client.post(self.profile_url, {"follow_or_unfollow": "follow_or_unfollow"})
formタグ内にactionを追加し、その部分に遷移するURLを書くと動くと思います。

2022-09-02 08:38 UTC, okapiinosuke commented on user/views.py
> +      my_follow[0].follow.add(follow_user)
まずはfollowerの方もForeignKeyで定義しなおしてください。
その後、get_or_createの行にfollowerも指定すると、addを消してもうまく動くと思います。

2022-09-03 01:17 UTC, takano630 commented on user/views.py
> +      my_follow[0].follow.add(follow_user)
'''
my_follow, created = FollowRelationship.objects.get_or_create(follower = user, followee = follow_user)
'''
addの部分消して上記の感じでget_or_createのところにfolloweeも指定してみたんですけどエラー出てしまいました
<img width="956" alt="image" src="https://user-images.githubusercontent.com/83489580/188249994-08706222-14c0-47ec-817c-562e20ecc47c.png">

2022-09-03 01:39 UTC, okapiinosuke commented on user/views.py
> +      my_follow[0].follow.add(follow_user)
一個前のコメントで書いたのですが、followerとfollowerどちらもForeignKeyを使って実装していますか？
エラーを見たところ、ManyToManyを使って実装したことが原因だと思います。

2022-09-03 02:19 UTC, takano630 commented on user/models.py
> +   follow = models.ManyToManyField('Account', related_name = 'followed', symmetrical = False, blank = True)
中間テーブルではManyToManyは使わない方がいいんですか？

2022-09-03 02:38 UTC, okapiinosuke commented on user/models.py
> +   follow = models.ManyToManyField('Account', related_name = 'followed', symmetrical = False, blank = True)
そうですね。
ManyToManyの中に中間テーブルを作成する機能があるので、中間テーブル内でそれを作ってしまうと、中間テーブルから更にまた別の中間テーブルを作ってしまうことになってしまいます。
公式ドキュメント
https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ManyToManyField

2022-09-03 04:40 UTC, takano630 commented on user/tests.py
> +    self.follow_response = self.client.post(self.profile_url, {"follow_or_unfollow": "follow_or_unfollow"})
formのaction追加したんですけどうまくいきませんでした...
エラーコードを乗せるの忘れてしまってすいません
<img width="721" alt="image" src="https://user-images.githubusercontent.com/83489580/188255978-d0ab5b8e-a8c0-45d5-ae27-a40a65fdbcd9.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/83489580/188255986-eeb72c14-96c0-4ce4-82a5-ed3ea650787c.png">
最後の方の「TypeError: 'AnonymousUser' object is not iterable」について調べたらログインしていないユーザーがアクセスしようとしているみたいなことが出てくるんですけど、
```
self.client.login(username='people', password='testpassword')
```
でログインしているはずなんですよね
やっぱりtest.pyのbuttonだけの時のpostの書き方が正しくないんですかね？

2022-09-04 01:38 UTC, okapiinosuke reviewed
コメントしました。
ProfileViewでのPOST周りを直すとうまく動作すると思います。
間違ったコメントでご迷惑をおかけしました。すみません。

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
> +    self.follow_response = self.client.post(self.profile_url, {"follow_or_unfollow": "follow_or_unfollow"})
私のコメントミスですね。すみません。ProfileViewにpostするのではなく、FollowViewにpostしましょう。
私もそうですが、どのViewが何の役割をしているかを考えて実装するとよいと思います。
そうしないと、バグが多いコードになりやすいです。

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
> +    self.people_follower_queryset = FollowRelationship.objects.filter(follower = self.people)
ここで呼び出して問題ないですか？
呼び出した時は何もフォロー関係がない状態なので、フォロー及びアンフォローをした後に呼び出した方がよいと思います。

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
> +    self.assertEqual(self.people_follower_queryset.count(), 0)
ここで先ほどのコメントのfilterの文を同時に呼び出す

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
> +    self.people_follower_queryset = FollowRelationship.objects.filter(follower = self.people)
フォローのテストの時と同様

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
> +    self.assertEqual(self.people_follower_queryset.count(), 1)
フォローのテストの時と同様

2022-09-04 01:38 UTC, okapiinosuke commented on templates/user/profile.html
> +    <form action="{% url 'profile' username %}" method="post">
follower=request.user、followee=Account.objects.filter(username=username)[0]（followee側の書き方は、あやふやな状態で書いているので要確認）の関係が存在するかどうかでどちらのview（FollowViewまたは、UnfollowView）に遷移するかを決めましょう。

2022-09-04 01:38 UTC, okapiinosuke commented on user/views.py
> +  def get(self, request, *args, **kwargs):
このコメントが理解ミスです。
FollowViewもしくはUnfollowViewにPOSTして、フォロー関係を作成、もしくは削除してください。

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
> +    self.assertEqual(self.people_follower_queryset.followee.all().count(), 1)
allではなく、filterを使う。

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
> +    self.assertEqual(self.people.follower.all().count(), 0)
こちらもallではなく、filter

2022-09-04 01:38 UTC, okapiinosuke commented on user/tests.py
>      self.profile_url = '/profile/'+self.people.username
URLの書き方をハードコーディング（直書き）ではなく、Reverseを使った書き方に直しましょう。
ほかの部分もそうしているところは書き直してください。
今回のテストからURLを指定する際には、reverseを使ってください。

2022-09-05 01:08 UTC, takano630 commented
テスト実行結果です
フォローでカウントが増えなかったのはユーザーを作るときのpkが被っててそもそもユーザーを２人作れていなかったことが原因でした
<img width="444" alt="image" src="https://user-images.githubusercontent.com/83489580/188341676-a5051b03-bc78-4f48-aecb-2ba50f5b7b46.png">

2022-09-05 08:16 UTC, okapiinosuke reviewed
コメントしました。
後は、フォロー、アンフォロー操作をpostでするだけです。
頑張ってください！

2022-09-05 08:16 UTC, okapiinosuke commented on user/tests.py
> +    self.follow_people = Account.objects.create_user(username='followpeople', email='test@test.test', password='testtestpassword', age='1', pk = '2')
pkはなくても大丈夫です。自動で登録されます。

2022-09-05 08:16 UTC, okapiinosuke commented on user/tests.py
> +    self.follow_people = Account.objects.create_user(username='follow_people', email='test@test.test', password='testpassword', age='1', pk = '2')
pkが不要

2022-09-05 08:16 UTC, okapiinosuke commented on user/views.py
>    def get(self, request, *args, **kwargs):
この処理をpostで行う。UnfollowViewでも同じ

2022-09-06 01:25 UTC, takano630 commented
test実行結果です
<img width="446" alt="image" src="https://user-images.githubusercontent.com/83489580/188527653-3593fe65-b8e3-4691-bae8-033b8ba2fc9d.png">

2022-09-06 01:27 UTC, takano630 commented
自分（フォローのボタンが消えてる）
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/188527800-d656ca06-1836-4445-b5c1-de7cf06f7e3f.png">
フォローしていないユーザー
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/188527709-70664c3f-4f42-4510-883f-d3a2ad0dd8d6.png">
フォロー済みのユーザー
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/188527755-517e3635-690d-4948-928f-8e81edc8b41a.png">

2022-09-06 01:40 UTC, okapiinosuke commented
LGTM！
2次レビューをお待ちください。

2022-09-07 03:41 UTC, Akinori13 requested changes
テストいい感じです！いくつかコメントしました

2022-09-07 03:41 UTC, Akinori13 commented on user/models.py
> +   followee = models.ForeignKey('Account', related_name = 'followed', on_delete=models.CASCADE)
followerとfolloweeの組み合わせがユニークになるようにお願いします

2022-09-07 03:41 UTC, Akinori13 commented on user/views.py
> +      return redirect('unfollow', name = follow_user.username)
followが既にあった場合に自動的に消去するのは設計上いいのか難しいですね
例えばFrontendで万が一二度クリックされた場合に、ユーザーの想定と全く結果が生まれるわけです。エラーを返すかそのままがベターかと思います

2022-09-07 03:41 UTC, Akinori13 commented on user/views.py
> +      FollowRelationship.objects.get_or_create(follower = user, followee = follow_user)
この時点で存在しないことは確定していませんか？

2022-09-07 03:41 UTC, Akinori13 commented on user/views.py
> +class UnFollowView(LoginRequiredMixin, View):
FollowVIewを参考に修正しましょう

2022-09-07 03:41 UTC, Akinori13 commented on user/tests.py
> +    self.people = Account.objects.create_user(username='people', email='test@test.test', password='testpassword', age='1')
単数形にしましょう

2022-09-07 03:41 UTC, Akinori13 commented on user/tests.py
> +    self.follow_people = Account.objects.create_user(username='followpeople', email='test@test.test', password='testtestpassword', age='1', pk = '2')
pk指定は必要ないですね
self.people.idみたいな感じで行けると思います

2022-09-07 03:41 UTC, Akinori13 commented on user/views.py
> +  context_object_name = 'follower_list'
ここにはFollowRelationshipのobjectsが格納されるので、follow_reloationshipsとかの方が良いと思います

2022-09-07 03:41 UTC, Akinori13 commented on user/views.py
> +    return user.followed.prefetch_related("follower").all()
ぱっとみselect_relatedが正しいように感じるのですが、ちょっとクエリを確認してもらいたいです！！

2022-09-07 04:33 UTC, takano630 commented
テスト実行結果です
<img width="563" alt="image" src="https://user-images.githubusercontent.com/83489580/188789390-dce96cb0-b6bf-4fd2-90b8-798b81fb63ab.png">

2022-09-07 04:38 UTC, takano630 commented on user/views.py
> +    return user.followed.prefetch_related("follower").all()
クエリセットの確認はこんな感じで大丈夫ですか？
<img width="441" alt="image" src="https://user-images.githubusercontent.com/83489580/188789804-28ff5821-8854-4d3d-928e-f37a736b88fa.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/83489580/188789820-b76f5a9a-a186-4010-a2a5-1eadc828523a.png">

2022-09-07 04:42 UTC, takano630 commented on user/views.py
> +    return user.followed.prefetch_related("follower").all()
１つのユーザーから複数のフォロー関係モデルの逆参照なので「prefetch」かなと思いました。
１つのモデルを参照するときが「select」で、複数の時は「prefetch」っていう認識だったんですけどあってますか？

2022-09-08 10:45 UTC, Akinori13 commented on user/views.py
> +    return user.followed.prefetch_related("follower").all()
many to manyのことを忘れていました！！そのままで！申し訳ないです！
QueryHistory使うといいかもですね！
```
from django.db import reset_queries
from django.db import connection
reset_queries()
for query in connection.queries:
    print(query)
```

2022-09-08 10:49 UTC, Akinori13 requested changes
少しだけコメントしました！

2022-09-08 10:49 UTC, Akinori13 commented on user/views.py
> +      FollowRelationship.objects.get(follower = user, followee = unfollow_user).delete()
my_followでいいのでは！

2022-09-08 10:49 UTC, Akinori13 commented on user/views.py
> +    context['follow_check'] = FollowRelationship.objects.filter(follower = self.request.user, followee = user_profile).exists()
命名はis~を使いましょう！

2022-09-08 10:49 UTC, Akinori13 commented on user/tests.py
> +    self.follow_people = Account.objects.create_user(username='follow_person', email='test@test.test', password='testpassword', age='1')
単数なら単数形を使うようにお願いします！

2022-09-09 06:47 UTC, takano630 commented
テスト実行結果です
<img width="447" alt="image" src="https://user-images.githubusercontent.com/83489580/189288406-59ccc9c0-491e-4a51-be12-a0caf63f6e27.png">

2022-09-09 16:33 UTC, Akinori13 requested changes
Okapiのレビューがいくつか修正されていないようです。[ここ](https://github.com/takano630/twittercloneapp/pull/6/files)の以下のファイルをチェックして修正をお願いします！！
- user/tests.py
- user/views.py

2022-09-09 16:33 UTC, Akinori13 commented on user/views.py
> +      pass
Okapiの指示に加えてここはエラーを返せるようにしてあげてください

2022-09-09 16:33 UTC, Akinori13 commented on user/tests.py
> +    self.assertEqual(self.people_follower_queryset.count(), 0)
ここはテンプレートのcontextのフォロワー数がself.people_follower_querysetと同じかのテストの方がいいですね

2022-09-10 03:00 UTC, takano630 commented
テスト実行結果です。指摘されたところは全部修正したつもりですが見逃し等あったら教えていただければ幸いです
<img width="444" alt="image" src="https://user-images.githubusercontent.com/83489580/189466198-a10630c6-6a95-4a84-8a8c-de222e17cc29.png">

2022-09-11 02:59 UTC, Akinori13 requested changes
1点だけコメントしました！

2022-09-11 02:59 UTC, Akinori13 commented on user/views.py
> +    else:
ここは400の方がいいですね（少なくとも404はNot Foundなので。）
それから以下のクエリが発行されるのがもったいないので、順番は106行より先の方がいいです。
```
my_follow = FollowRelationship.objects.filter(follower = user, followee = unfollow_user)
```

2022-09-11 13:14 UTC, takano630 commented
test実行結果です
<img width="440" alt="image" src="https://user-images.githubusercontent.com/83489580/189529532-8adb37a6-97cd-460d-ba89-cbc19eaa86b9.png">

2022-09-11 14:20 UTC, Akinori13 commented on user/views.py
> +      FollowRelationship.objects.filter(follower = user, followee = unfollow_user).delete()
ここはexists()で存在チェックしてから削除するのがベターですがこのままでも構いません

2022-09-11 14:20 UTC, Akinori13 commented
LGTM

2022-09-11 14:20 UTC, merged