いいね機能を作りました
takano630/twittercloneapp pull request #7
Opened 2022-09-12 07:18 UTC by takano630

いいね機能を作りました。
homeとprofileのツイートの部分に「like」ボタンを作成しました
<img width="943" alt="image" src="https://user-images.githubusercontent.com/83489580/189594406-8f280948-c2ca-45d3-a786-1555c1f63bd5.png">
<img width="921" alt="image" src="https://user-images.githubusercontent.com/83489580/189594470-903e6e81-7c73-4cc5-bd44-c627eb6267f0.png">
すでにいいね済みの場合は「unlike」に変わります
<img width="522" alt="image" src="https://user-images.githubusercontent.com/83489580/189594662-2624a778-0e28-4c8d-ae37-38098e86aad9.png">
ツイート詳細画面でいいね数を確認できます
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83489580/189594944-57e55ebd-69c5-4ee3-a843-ad5a79f747fd.png">

2022-09-12 09:36 UTC, takano630 commented
test実行結果です
<img width="428" alt="image" src="https://user-images.githubusercontent.com/83489580/189621664-65ab4ee6-6283-42ac-a5a6-c2f46bb95843.png">

2022-09-13 06:19 UTC, takano630 commented
実行結果です
<img width="451" alt="image" src="https://user-images.githubusercontent.com/83489580/189824811-61028348-1d92-466b-b25b-d14dd7ece5e7.png">

2022-09-14 14:54 UTC, Akinori13 commented
いいね、いいね取消機能はAjaxのFetchAPIで実装してください！

2022-09-18 02:53 UTC, takano630 commented
ボタンを押すたびに「いいね」「いいね解除」の表示が切り替わるようにしました。
profile画面のツイート一覧でも同様になってます。
<img width="939" alt="image" src="https://user-images.githubusercontent.com/83489580/190883484-1deac159-df2e-42ae-a472-25316f46510d.png">

2022-09-18 02:54 UTC, takano630 commented
テスト実行結果です
<img width="435" alt="image" src="https://user-images.githubusercontent.com/83489580/190883569-105674d1-a73f-454e-bcbb-af9b0e8cb52e.png">

2022-09-18 04:31 UTC, Akinori13 requested changes
Ajax使えていい感じです！！コメントしました

2022-09-18 04:31 UTC, Akinori13 commented on templates/user/home.html
> +        </script>
この実装だとTweetが100個あれば100個のScriptが生成されることになりませんか？
data属性を使ってTweetのIDと当該ツイートのいいね状態（いいねされているか・されていないのか）を取得し、それにしたがって、いいねまたはいいね取消にPOSTするようにしてあげましょう！

2022-09-18 04:31 UTC, Akinori13 commented on user/views.py
> +@login_required
likeとunlikeはエンドポイントを分けてあげてください！

2022-09-18 04:31 UTC, Akinori13 commented on templates/user/home.html
> +            $.ajax({
本来はfetch使ってほしいですが、このまま進めてokです

2022-09-19 13:13 UTC, takano630 commented
いいねの状態によってhtmlを書き換えてpostするurlを変えようとしたんですけど行き詰ってしまいました...
ボタンを押すとボタンが二重？になって一度押しても複数押したことになって挙動がおかしくなってしまいました。
ソースを表示してもボタンは一つになっているように見えるのですが...
<img width="525" alt="image" src="https://user-images.githubusercontent.com/83489580/191024067-854de13b-9a67-4555-bb82-ccdf3915f88f.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/83489580/191024192-7fb2a91e-4428-4ade-a9d5-558eb5213378.png">

2022-09-20 02:57 UTC, Akinori13 requested changes
コメントしました！

2022-09-20 02:57 UTC, Akinori13 commented on templates/user/home.html
> +                like_text.innerHTML = '<button id= "like{{ tweet.pk }}" type="submit" data_liked= "True" class="like_button {{ tweet.pk }}">いいね解除</button>';
ここでbuttonの中にボタンを作ってしまってないですか？

2022-09-20 02:57 UTC, Akinori13 commented on templates/user/home.html
> +              let like_text = document.getElementsByClassName("like_button {{ tweet.pk }}")[0];
classnameでの指定はあまり良くないです。data属性かidで検索、もくしくevent.targetが使えるかもです！

2022-09-20 06:07 UTC, takano630 commented
test実行結果です
<img width="427" alt="image" src="https://user-images.githubusercontent.com/83489580/191179920-8fe996f5-8522-4304-88bb-bdafa66a3683.png">

2022-09-20 06:08 UTC, takano630 commented on templates/user/home.html
> +                like_text.innerHTML = '<button id= "like{{ tweet.pk }}" type="submit" data_liked= "True" class="like_button {{ tweet.pk }}">いいね解除</button>';
解決しました！！！ありがとうございました

2022-09-21 06:36 UTC, Akinori13 requested changes
少しコメントしました！

2022-09-21 06:36 UTC, Akinori13 commented on user/views.py
> +    liked = False
raise BadRequestで400返すので、likedはいらないのではありませんか。
またis_likedの方が命名規則としては良いでしょう！

2022-09-21 06:36 UTC, Akinori13 commented on user/views.py
> +    liked = True
同様

2022-09-21 11:41 UTC, takano630 commented
test実行結果です
<img width="431" alt="image" src="https://user-images.githubusercontent.com/83489580/191495087-8bcb4963-2a40-4a17-ac73-5d3cf4b3463e.png">

2022-09-22 03:28 UTC, Akinori13 commented
LGTM

2022-09-22 03:28 UTC, Akinori13 approved these changes

2022-09-22 03:29 UTC, merged